"""Add description to pipeline model

Revision ID: 6d56d709b542
Revises: e02c36ce63fa
Create Date: 2024-02-03 17:34:58.235640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d56d709b542'
down_revision: Union[str, None] = 'e02c36ce63fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'description')
    # ### end Alembic commands ###
