"""Try to fix bug.

Revision ID: 714da875d6be
Revises: 21b101d611f7
Create Date: 2024-02-06 02:39:09.741117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714da875d6be'
down_revision: Union[str, None] = '21b101d611f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('is_detected', sa.Boolean(), nullable=True))
    op.add_column('car', sa.Column('coordinates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'coordinates')
    op.drop_column('car', 'is_detected')
    # ### end Alembic commands ###
