"""Add func column to step

Revision ID: b2921611e803
Revises: 95ae34436add
Create Date: 2024-02-05 15:53:19.404035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2921611e803'
down_revision: Union[str, None] = '95ae34436add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('func', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'func')
    # ### end Alembic commands ###
