"""Redifine tables relations to Many-To-Many

Revision ID: c70bc285cb35
Revises: c4517badd28a
Create Date: 2024-02-04 20:41:01.315149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70bc285cb35'
down_revision: Union[str, None] = 'c4517badd28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_step',
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('pipeline_id', 'step_id')
    )
    op.drop_constraint('step_pipeline_id_fkey', 'step', type_='foreignkey')
    op.drop_column('step', 'pipeline_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('pipeline_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('step_pipeline_id_fkey', 'step', 'pipeline', ['pipeline_id'], ['id'])
    op.drop_table('pipeline_step')
    # ### end Alembic commands ###
